Repository hydroshare/hydroshare, pull requests merged in 2018-06, with the labels that each got.

#2766 changed salutation
  hs_core/tasks.py
Labels: in progress

#2769 Fixing JSON-LD errors and adding fields back to admin
  hs_core/admin.py
  theme/templates/resource-landing-page/title-section.html
Labels: in progress

#2764 Composite resource usability improvements
  hs_core/templates/pages/genericresource.html
  hs_file_types/models/generic.py
  hs_file_types/models/geofeature.py
  hs_file_types/models/netcdf.py
  hs_file_types/models/raster.py
  hs_file_types/models/reftimeseries.py
  hs_file_types/models/timeseries.py
  theme/static/js/composite-resource.js
  theme/static/js/coverageMap.js
  theme/static/js/hs_file_browser.js
  theme/static/js/resourceLandingAjax.js
  theme/templates/resource-landing-page/coverage.html
Labels: Composite, in progress

#2767 2567 path app launch
  hs_composite_resource/models.py
  hs_composite_resource/tests/test_composite_resource_auto_aggregate.py
  hs_core/hydroshare/resource.py
  hs_core/templates/pages/genericresource.html
  hs_core/templates/pages/metadata_terms.html
  hs_core/views/resource_folder_hierarchy.py
  hs_file_types/models/base.py
  hs_file_types/models/geofeature.py
  hs_file_types/models/netcdf.py
  hs_file_types/models/raster.py
  hs_file_types/models/reftimeseries.py
  hs_file_types/models/timeseries.py
  hs_file_types/tests/test_generic_metadata.py
  hs_file_types/tests/test_geofeature_metadata.py
  hs_file_types/tests/test_netcdf_metadata.py
  hs_file_types/tests/test_raster_metadata.py
  hs_file_types/tests/test_reftimeseries_metadata.py
  hs_file_types/tests/test_timeseries_metadata.py
  hs_file_types/utils.py
  hs_tools_resource/app_launch_helper.py
  hs_tools_resource/forms.py
  hs_tools_resource/migrations/0018_auto_20180530_2246.py
  hs_tools_resource/migrations/0019_auto_20180531_2304.py
  hs_tools_resource/migrations/0020_auto_20180604_1845.py
  hs_tools_resource/models.py
  hs_tools_resource/page_processors.py
  hs_tools_resource/receivers.py
  hs_tools_resource/serializers.py
  hs_tools_resource/static/css/toolresource.css
  hs_tools_resource/templates/pages/toolresource.html
  hs_tools_resource/tests/test_web_app.py
  hs_tools_resource/tests/test_web_app_validation.py
  theme/static/css/hydroshare_core.css
  theme/static/js/create-resource.js
  theme/static/js/hs_file_browser.js
  theme/static/js/resourceLandingAjax.js
  theme/templates/resource-landing-page/title-section.html
Labels: Composite

#2718 1842 nginx sendfile
  .gitignore
  Dockerfile
  hs_core/hydroshare/hs_requests.py
  hs_core/management/commands/check_bag.py
  hs_core/management/commands/check_sizes.py
  hs_core/management/commands/check_uri.py
  hs_core/management/commands/debug_resource.py
  hs_core/models.py
  hs_core/serialization.py
  hs_core/tasks.py
  hs_core/tests/api/native/test_clean_for_xml.py
  hs_core/tests/api/native/test_folder_download_zip.py
  hs_core/tests/api/native/test_hs_requests.py
  hs_core/views/__init__.py
  hs_core/views/resource_rest_api.py
  hsctl
  hydroshare/local_settings.py
  hydroshare/settings.py
  nginx/Dockerfile.template
  nginx/config-files/hydroshare-nginx.conf
  nginx/config-files/hydroshare-nginx.conf.template
  nginx/config-files/hydroshare-ssl-nginx.conf.template
  nginx/config-files/nginx.conf-default.template
  nginx/run-nginx
  ref_ts/views.py
  scripts/templates/docker-compose.template
  scripts/templates/init-hydroshare.template
Labels: in progress
