Repository hydroshare/hydroshare, pull requests merged in 2019-02, with the labels that each got.

#2983 2955 inform accurately the status of resource
  theme/static/js/resourceLandingAjax.js
Labels: in progress

#3121 [#3080] pull in work for patch release
  hs_tracking/management/commands/stats.py
Labels: in progress

#3123 fixed issue #2276
  hs_core/hydroshare/utils.py
Labels: in progress

#3114 Remove unused redis
  .gitignore
  Dockerfile
  Dockerfile-hydroshare
  alternate-compose.yml
  config/hydroshare-config.yaml
  hydroshare/local_settings.cutover
  hydroshare/local_settings.template
  hydroshare/settings.desired
  irods/README.md
  run-tests-jenkins
  scripts/templates/docker-compose-local-irods.template
  scripts/templates/docker-compose.template
Labels: in progress

#3134 further fix to issue #2276
  hs_core/autocomplete_light_registry.py
  hs_core/templatetags/hydroshare_tags.py
  theme/templates/includes/profile-link.html
Labels: in progress

#3142 [#3138] Correctly trigger removing self access in Manage Access panel
  theme/static/js/resourceLandingAjax.js
  theme/templates/resource-landing-page/quota.html
Labels: User Interface, in progress

#3132 2946 improve geofeature parsing error msg
  hs_file_types/models/geofeature.py
Labels: in progress

#3116 Fix for timeseries auto aggegation from CSV file
  hs_composite_resource/tests/data/ODM2_One_Site_One_Series_Test.csv
  hs_composite_resource/tests/test_composite_resource_auto_aggregate.py
  hs_core/hydroshare/utils.py
Labels: in progress

#3105 1632 reorganize access control
  hs_access_control/models/README.md
  hs_access_control/models/__init__.py
  hs_access_control/models/group.py
  hs_access_control/models/privilege.py
  hs_access_control/models/provenance.py
  hs_access_control/models/resource.py
  hs_access_control/models/user.py
  hs_access_control/models/utils.py
  setup.cfg
Labels: in progress

#3133 3088 hsapi
  hs_access_control/models/privilege.py
  hs_access_control/tests/test_share_resource.py
  hs_core/hydroshare/resource.py
  hs_core/hydroshare/users.py
  hs_core/models.py
  hs_core/tests/api/native/test_get_resource_file.py
  hs_core/tests/api/native/test_update_resource_file.py
  hs_core/tests/api/rest/test_create_resource.py
  hs_core/tests/api/rest/test_resource_file.py
  hs_core/tests/api/rest/test_resource_list.py
  hs_core/tests/api/rest/test_resource_meta.py
  hs_core/tests/api/rest/test_resource_science_meta.py
  hs_core/tests/api/rest/test_resource_types.py
  hs_core/tests/api/rest/test_set_access_rules.py
  hs_core/views/resource_rest_api.py
  hs_core/views/serializers.py
  hs_rest_api/resources/file_metadata.py
  hs_rest_api/tests/http/test_file_metadata.py
  hs_rest_api/urls.py
  hs_rest_api/views/__init__.py
  hs_rest_api/views/hs_core.py
  run-tests-jenkins
Labels: in progress

#3170 Updated irods/README.md to include a line about creating local_settin…
  irods/README.md
Labels: Documentation

#3173 Fix for geo feature coverage display
  hs_file_types/models/netcdf.py
  hs_file_types/models/timeseries.py
  theme/static/js/resourceLandingAjax.js
Labels: in progress
