Repository hydroshare/hydroshare, pull requests merged in 2019-03, with the labels that each got.

#3188 [#3167] Add table column sort indicator
  theme/static/css/jquery.dataTables.min.css
  theme/static/img/sort_asc.png
  theme/static/img/sort_asc_disabled.png
  theme/static/img/sort_both.png
  theme/static/img/sort_desc.png
  theme/static/img/sort_desc_disabled.png
Labels: User Interface

#3106 [#2638] Edit to text on My Resources
  hs_core/templates/pages/my-resources.html
  hs_core/templates/search/search.html
Labels: (1) Small Effort, User Interface, in progress

#3189 [WIP][#3136] Move Copy Resource Bag button to file browser's toolbar
  hs_core/templates/pages/genericresource.html
  theme/static/css/hydroshare_core.css
Labels: User Interface

#3184 [#3183] Hide items in Comments section
  theme/static/css/hydroshare_extends.css
  theme/templates/generic/includes/comments.html
  theme/templatetags/comments_tags.py
Labels: User Interface

#3112 [#2813] Add Metadata/Set content type - Enhancements
  hs_core/templates/pages/genericresource.html
  theme/static/js/hs_file_browser.js
  theme/templates/resource-landing-page/modals.html
Labels: in progress

#3109 [#2989] Update cursor settings for various elements
  hs_core/templates/pages/create-resource.html
  hs_core/templates/pages/my-resources.html
  hs_core/templates/search/search.html
  theme/static/css/hydroshare_core.css
Labels: (1) Small Effort, User Interface, in progress

#3108 [#2765] Fix for text input auto select on Zip Folder dialog
  theme/static/js/hs_file_browser.js
Labels: (1) Small Effort, User Experience, in progress

#3124 Additional timeseries csv file validation
  hs_app_timeseries/tests/Invalid_Date_Numeric.csv
  hs_app_timeseries/tests/Invalid_One_Data_Row.csv
  hs_file_types/models/timeseries.py
  hs_file_types/tests/data/valid_two_data_rows.csv
  hs_file_types/tests/test_timeseries_metadata.py
Labels: in progress

#3131 [#3130] Make metadata alert persist until all required metadata is filled in
  theme/static/css/hydroshare_core.css
  theme/static/js/generic-resource.js
  theme/static/js/resourceLandingAjax.js
Labels: User Interface, in progress

#3111 [#3110] Resource Landing Page - Minor fixes
  hs_collection_resource/templates/pages/collectionresource.html
  theme/static/js/hs_file_browser.js
  theme/templates/resource-landing-page/coverage.html
Labels: (1) Small Effort, User Interface, in progress

#3150 2823 check profile image size before upload
  theme/static/css/hydroshare_core.css
  theme/static/js/profile.js
  theme/templates/accounts/profile.html
Labels: in progress

#3101 Migrate generic resources to composite resource
  hs_core/hydroshare/hs_bagit.py
  hs_core/management/commands/migrate_generic_resources.py
Labels: in progress

#3060 3045 web services
  hs_core/models.py
  hs_core/receivers.py
  hs_core/signals.py
  hs_core/tasks.py
  hs_core/views/__init__.py
  hs_core/views/resource_rest_api.py
  hs_core/views/serializers.py
  hs_file_types/models/base.py
  hs_file_types/models/generic.py
  hs_file_types/models/geofeature.py
  hs_file_types/models/netcdf.py
  hs_file_types/models/raster.py
  hs_file_types/models/reftimeseries.py
  hs_file_types/models/timeseries.py
  hydroshare/local_settings.cutover
  hydroshare/local_settings.template
Labels: in progress

#3235 3234 nav bar
  hs_core/templates/400.html
  hs_core/templates/404.html
  hs_core/templates/500.html
  hs_core/templates/503.html
  theme/templates/base.html
  theme/templates/pages/menus/dropdown.html
Labels: in progress

#3182 [#3165] Remove THREDDS Data Service message from multidimensional landing page
  hs_app_netCDF/page_processors.py
  hs_app_netCDF/templates/pages/netcdfresource.html
Labels: User Interface

#3252 [#3251] Fix download through license agreement
  theme/static/js/hs_file_browser.js
Labels: High Priority
